### ISSUE TITLE
Excessive Memory Consumption for 3D Files

### ISSUE THREAD

**Issue by waltsims** [yanlend/mhd_utils#4]
I'm trying to write an .mhd file of 3D time-series data with an 'ElementNumbeOfChannels' value of 64. The file should be ~2GB when written to disk, but some point in the dump_raw processing takes ~40 GB of RAM. Have others experienced this same issue? Is it known?

**Comment by yanlend** [comment]
Conversion to a list is unnecessary. However, your proposed solution to convert to string is also not ideal, e.g. it could loose precision.

I am currently rewriting it a bit and in the process will remove the conversion. Numpy arrays can directly write binary files.

**Comment by waltsims** [comment]
sounds good.

**Comment by yanlend** [comment]
It should be fixed. Please try it with your data if you still need it.
