### ISSUE TITLE
Question about `pwd` logic when loading mhd

### ISSUE THREAD

**Issue by asanin-epfl** [yanlend/mhd_utils#6]
Hi! Thank you for the library.

My question is about https://github.com/yanlend/mhd_utils/blob/master/mhd_utils/__init__.py#L84.

In case when `meta_dict['ElementDataFile']` contains an absolute filepath, and we do `load_raw_data_with_mhd(another_absolute_filepath)` => an error is raised because we concatenate both absolute filepaths: `data_file = pwd + '/' + meta_dict['ElementDataFile']`. Could we make this logic with `pwd` optional or remove it at all? I can prepare a PR, if you want.

All the best

**Comment by yanlend** [comment]
In my opinion, absolute file paths don't make much sense for the this format. Usually, the `raw` file and the `mhd` file are in the same folder. With absolute paths, you cannot move the image to a different path without editing the `mhd`

**Comment by yanlend** [comment]
Technically, it would not be an issue to implement this.

**Comment by asanin-epfl** [comment]
Would it be possible to make a flag argument that switches this behavior?
```
def load_raw_data_with_mhd(filename, pwd=True):
```
By default it would be the existing behavior but with `pwd=False` we can turn it off.

**Comment by yanlend** [comment]
I updated the package, it should work now. Can you try it please?

**Comment by asanin-epfl** [comment]
Yep, it works. Thank you!
